const KEY="familyPlannerLocalV2";
const NAV=[["home","⌂","Home"],["food","◫","Food"],["meals","◉","Meals"],["groceries","✓","List"],["budget","$","Budget"],["driving","↗","Drive"]];
const RECIPES=[
{id:"greekChicken",name:"Greek Chicken",servings:6,cost:10,tags:["protein"],q:"Greek chicken recipe",ing:[["chicken",2,"lb"],["lemon",2,"count"],["plain yogurt",8,"oz"]]},
{id:"bakedPotato",name:"Baked Potato Night",servings:4,cost:6,tags:["cheap","calcium"],q:"baked potato dinner recipe",ing:[["russet potatoes",2,"lb"],["cheddar",6,"oz"],["sour cream",8,"oz"]]},
{id:"chickenPasta",name:"Creamy Chicken Pasta",servings:6,cost:9,tags:["protein","calcium"],q:"creamy chicken pasta recipe",ing:[["chicken",1,"lb"],["pasta",16,"oz"],["cream",8,"oz"],["Parmesan",4,"oz"]]},
{id:"pizza",name:"Sheet Pan Cheese Pizza",servings:6,cost:9,tags:["cheap","calcium"],q:"sheet pan cheese pizza recipe",ing:[["flour",32,"oz"],["pizza sauce",14,"oz"],["mozzarella",16,"oz"]]},
{id:"chili",name:"Bean Chili",servings:6,cost:8,tags:["cheap","protein"],q:"budget bean chili recipe",ing:[["beans",3,"cans"],["diced tomatoes",2,"cans"],["onion",1,"count"]]},
{id:"mac",name:"Homemade Mac & Cheese",servings:4,cost:5,tags:["cheap","calcium"],q:"homemade mac and cheese recipe",ing:[["macaroni",8,"oz"],["cheddar",8,"oz"],["milk",12,"oz"]]},
{id:"chickenRice",name:"Chicken & Rice",servings:6,cost:8,tags:["cheap","protein"],q:"budget chicken and rice recipe",ing:[["rice",12,"oz"],["chicken",1,"lb"],["mixed vegetables",12,"oz"]]},
{id:"pastaCeci",name:"Pasta e Ceci",servings:4,cost:6,tags:["cheap","protein"],q:"site:giallozafferano.com pasta e ceci recipe",ing:[["pasta",12,"oz"],["chickpeas",2,"cans"],["tomato paste",1,"can"]]}
];
const blank=()=>({version:2,profileLoaded:false,view:"home",householdLabel:"My Household",ebtBudget:0,dinnerSlots:30,zip:"",prices:[],essentials:[],plan:{},cooked:{},purchased:{},purchaseCost:{},income:{salaryAnnual:0,withholdingPct:0,tipNights:0,tipsAvg:0,tipsLow:0,tipsHigh:0,note:""},bills:[],dailyExpenses:[],otherCash:0,fuel:{pricePerGal:0,priceUpdated:"",mpg:"",station:"",routes:[]}});
let state=(()=>{try{return Object.assign(blank(),JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return blank()}})();
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], n=v=>Number.isFinite(+v)?+v:0, money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n(v)), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m])), search=q=>"https://www.google.com/search?q="+encodeURIComponent(q);
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)), ym=()=>new Date().toISOString().slice(0,7), days=()=>new Date(new Date().getFullYear(),new Date().getMonth()+1,0).getDate();
const mdiff=(a,b)=>{let A=(a||ym()).split("-").map(Number),B=(b||ym()).split("-").map(Number);return(B[0]-A[0])*12+B[1]-A[1]};
const due=b=>{let d=mdiff(b.startMonth,ym());return d>=0&&d%Math.max(1,n(b.frequencyMonths)||1)===0};
const essentialsTotal=()=>state.essentials.reduce((s,e)=>s+n(e.qty)*n(e.unitPrice),0);
const planTotal=()=>Object.entries(state.plan).reduce((s,[id,c])=>s+n(c)*(RECIPES.find(r=>r.id===id)?.cost||0),0);
const foodLeft=()=>n(state.ebtBudget)-essentialsTotal()-planTotal();
const batches=()=>Object.values(state.plan).reduce((a,b)=>a+n(b),0), slots=()=>Math.max(0,n(state.dinnerSlots)-batches()), target=()=>slots()?Math.max(0,foodLeft()/slots()):0;
const repeats=r=>Math.max(0,Math.min(slots(),Math.floor(Math.max(0,foodLeft())/Math.max(.01,r.cost))));
const salaryGross=()=>n(state.income.salaryAnnual)/12, salaryNet=()=>salaryGross()*(1-n(state.income.withholdingPct)/100), tips=rate=>n(rate??state.income.tipsAvg)*n(state.income.tipNights)*52/12, income=()=>salaryNet()+tips();
const billsMonth=()=>state.bills.filter(due).reduce((s,b)=>s+n(b.amount),0), billsAvg=()=>state.bills.reduce((s,b)=>s+n(b.amount)/Math.max(1,n(b.frequencyMonths)||1),0);
const dailyMonth=()=>state.dailyExpenses.reduce((s,d)=>s+n(d.amountPerDay)*days(),0), weeklyMiles=()=>state.fuel.routes.reduce((s,r)=>s+(n(r.miles)>0&&n(r.days)>0?n(r.miles)*n(r.days):0),0), monthlyMiles=()=>weeklyMiles()*4.345;
const fuelCost=()=>n(state.fuel.mpg)>0?monthlyMiles()/n(state.fuel.mpg)*n(state.fuel.pricePerGal):null, cashLeft=()=>income()-billsMonth()-dailyMonth()-(fuelCost()||0)-n(state.otherCash);
function grocery(){let m={};const add=(name,q,u,src)=>{let k=name+"|"+u;if(!m[k])m[k]={key:k,name,qty:0,unit:u,sources:new Set};m[k].qty+=n(q);m[k].sources.add(src)};state.essentials.forEach(e=>n(e.qty)>0&&add(e.name,e.qty,e.unit,"essential"));Object.entries(state.plan).forEach(([id,c])=>{let r=RECIPES.find(x=>x.id===id);if(r)r.ing.forEach(i=>add(i[0],i[1]*n(c),i[2],r.name))});return Object.values(m)}
function shell(){document.querySelector("#app").innerHTML=`
<div class="shell">
<header class="top"><div class="topin"><div class="brand"><div class="logo">FP</div><div><b>Family Planner</b><small id="labelTop"></small></div></div><div class="pill">Standalone · local-only data</div></div></header>
<nav class="tabs" id="tabs"></nav>
<main>
<section class="view" data-v="home"><div class="hero"><div class="panel"><div class="eyebrow">Separate origin</div><h1>Food, bills and driving — isolated from Shaelvien.</h1><p class="muted">This public app shell contains no household profile values. Import your private JSON on this device to use your real numbers.</p><div class="notice section" id="setup"></div></div><div class="panel"><div class="eyebrow">This month</div><div class="value greenText" id="cashHero"></div><div class="kpi section"><span>Food remaining</span><b id="foodHero"></b></div><div class="kpi"><span>Known miles</span><b id="milesHero"></b></div><div class="kpi"><span>Fuel</span><b id="fuelHero"></b></div></div></div><div class="grid g4 stats section" id="homeStats"></div></section>
<section class="view" data-v="food"><div class="panel"><div class="split"><div><div class="eyebrow">Food</div><h2>Essentials + manual price references</h2><p class="muted">Search buttons open a normal browser search. Nothing is pulled back automatically.</p></div><div class="stat"><small>Food remaining</small><div class="value greenText" id="foodRemain"></div></div></div></div><div class="card section"><div class="split"><h2>Prices</h2><button class="btn" id="addPrice">+ Item</button></div><div class="tablewrap section"><table><thead><tr><th>Item</th><th>Pack</th><th>Price</th><th>Store</th><th></th></tr></thead><tbody id="priceRows"></tbody></table></div></div><div class="card section"><div class="split"><h2>Monthly essentials</h2><button class="btn" id="addEssential">+ Essential</button></div><div class="tablewrap section"><table><thead><tr><th>Item</th><th>Qty</th><th>Unit</th><th>Price</th><th>Total</th><th></th></tr></thead><tbody id="essentialRows"></tbody></table></div></div></section>
<section class="view" data-v="meals"><div class="panel"><div class="split"><div><div class="eyebrow">Meals</div><h2>Budget-aware picker</h2></div><div class="stat"><small>Target / remaining dinner</small><div class="value blueText" id="mealTarget"></div></div></div><div class="tools section"><input class="field" id="mealSearch" placeholder="Meal idea"><button class="btn primary" id="recipeSearch">Search under target</button></div></div><div class="grid g3 section" id="recipes"></div><div class="card section"><div class="split"><h2>Planned meals</h2><small id="mealMeta"></small></div><div id="planRows"></div></div></section>
<section class="view" data-v="groceries"><div class="panel"><div class="split"><div><div class="eyebrow">Groceries</div><h2>Generated shopping list</h2></div><div class="stat"><small>Purchased</small><div class="value greenText" id="purchasePct"></div></div></div></div><div class="card section" id="shopping"></div></section>
<section class="view" data-v="budget"><div class="panel"><div class="split"><div><div class="eyebrow">Budget</div><h2>Cash income, bills and daily expenses</h2></div><div class="stat"><small>Unallocated cash</small><div class="value amberText" id="budgetLeft"></div></div></div></div><div class="grid g2 section"><div class="card"><h2>Income</h2><div class="grid g2 section"><label><span>Annual salary</span><input class="field income" data-k="salaryAnnual" type="number"></label><label><span>Withholding %</span><input class="field income" data-k="withholdingPct" type="number"></label><label><span>Tip nights/week</span><input class="field income" data-k="tipNights" type="number"></label><label><span>Average tips/night</span><input class="field income" data-k="tipsAvg" type="number"></label><label><span>Low tips/night</span><input class="field income" data-k="tipsLow" type="number"></label><label><span>High tips/night</span><input class="field income" data-k="tipsHigh" type="number"></label></div><label class="section"><span>Notes / deductions not modeled</span><textarea class="field" id="incomeNote"></textarea></label><div id="incomeSummary" class="section"></div></div><div class="card"><h2>Cash picture</h2><div id="cashSummary" class="section"></div><label class="section"><span>Other / unlisted expenses</span><input class="field" id="otherCash" type="number"></label></div></div><div class="card section"><div class="split"><h2>Bills</h2><button class="btn" id="addBill">+ Bill</button></div><div class="tablewrap section"><table><thead><tr><th>Bill</th><th>Amount</th><th>Due</th><th>Every N mo</th><th>Starts</th><th></th></tr></thead><tbody id="billRows"></tbody></table></div></div><div class="card section"><div class="split"><h2>Daily cash expenses</h2><button class="btn" id="addDaily">+ Daily</button></div><div id="dailyRows"></div></div></section>
<section class="view" data-v="driving"><div class="panel"><div class="split"><div><div class="eyebrow">Driving</div><h2>Route-based fuel estimate</h2></div><div class="stat"><small>Monthly fuel</small><div class="value amberText" id="fuelEstimate"></div></div></div></div><div class="grid g3 section"><label class="card"><span>Gas price / gallon</span><input class="field" id="gasPrice" type="number" step=".01"></label><label class="card"><span>Vehicle MPG</span><input class="field" id="mpg" type="number" step=".1"></label><div class="card"><label><span>Station / search phrase</span><input class="field" id="station"></label><a class="btn section" id="gasSearch" target="_blank" rel="noopener">Check gas price</a></div></div><div class="grid g4 stats section" id="driveStats"></div><div class="card section"><div class="split"><h2>Route legs</h2><button class="btn" id="addRoute">+ Route</button></div><div class="tablewrap section"><table><thead><tr><th>Route</th><th>Miles</th><th>Days/week</th><th>Weekly</th><th></th></tr></thead><tbody id="routeRows"></tbody></table></div></div></section>
<section class="view" data-v="settings"><div class="panel"><div class="eyebrow">Settings</div><h2>Private profile + backup</h2><p class="muted">Your data stays in this browser unless you export it yourself.</p></div><div class="card section"><div class="grid g3"><label><span>Household label</span><input class="field" id="houseLabel"></label><label><span>Food budget</span><input class="field" id="ebtBudget" type="number"></label><label><span>Dinner slots</span><input class="field" id="dinnerSlots" type="number"></label><label><span>ZIP for manual searches</span><input class="field" id="zip"></label></div><div class="tools section"><label class="btn primary">Import private profile<input hidden id="importFile" type="file" accept="application/json"></label><button class="btn" id="exportBtn">Export backup</button><button class="btn danger" id="resetBtn">Clear device</button></div><div class="notice section">Internet boundary: searches open in a separate browser page. Search results never write into planner storage automatically.</div><div class="notice section"><b>iPhone:</b> Safari → Share → Add to Home Screen.</div></div></section>
</main></div><div class="bottom" id="bottom"></div>`;
}
function nav(){let top=NAV.map(x=>`<button data-nav="${x[0]}">${x[2]}</button>`).join("")+`<button data-nav="settings">Settings</button>`;$("#tabs").innerHTML=top;$("#bottom").innerHTML=NAV.map(x=>`<button data-nav="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join("");$$("[data-nav]").forEach(b=>b.onclick=()=>show(b.dataset.nav))}
function show(v){state.view=v;$$(".view").forEach(x=>x.classList.toggle("active",x.dataset.v===v));$$("[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===v));save();scrollTo({top:0,behavior:"smooth"})}
function render(){
$("#labelTop").textContent=(state.householdLabel||"My Household")+" · local-only";
$("#setup").textContent=state.profileLoaded?"Private profile loaded on this device.":"No private profile loaded yet. Open Settings to import your Drive JSON.";
$("#cashHero").textContent=state.profileLoaded?money(cashLeft()):"Import profile";$("#foodHero").textContent=state.profileLoaded?money(foodLeft()):"—";$("#milesHero").textContent=state.profileLoaded?Math.round(monthlyMiles()).toLocaleString()+" mi":"—";$("#fuelHero").textContent=fuelCost()==null?"Enter MPG":money(fuelCost());
$("#homeStats").innerHTML=[["Modeled cash income",money(income())],["Bills due",money(billsMonth())],["Food remaining",money(foodLeft())],["Daily expenses",money(dailyMonth())]].map(x=>`<div class="stat"><small>${x[0]}</small><div class="value">${x[1]}</div></div>`).join("");
$("#foodRemain").textContent=money(foodLeft());
$("#priceRows").innerHTML=state.prices.map((x,i)=>`<tr><td><input class="field pn" data-i="${i}" value="${esc(x.name)}"></td><td><input class="field pp" data-i="${i}" value="${esc(x.pack||"")}"></td><td><input class="field pv" data-i="${i}" type="number" step=".01" value="${n(x.price)}"></td><td><input class="field ps" data-i="${i}" value="${esc(x.store||"")}"></td><td><a class="btn" target="_blank" rel="noopener" href="${search((x.name||"grocery")+" price "+(x.store||"")+" "+state.zip)}">Search</a></td></tr>`).join("")||`<tr><td colspan="5"><div class="empty">No price references yet.</div></td></tr>`;
$("#essentialRows").innerHTML=state.essentials.map((e,i)=>`<tr><td><input class="field en" data-i="${i}" value="${esc(e.name)}"></td><td><input class="field eq" data-i="${i}" type="number" value="${n(e.qty)}"></td><td><input class="field eu" data-i="${i}" value="${esc(e.unit||"item")}"></td><td><input class="field ep" data-i="${i}" type="number" step=".01" value="${n(e.unitPrice)}"></td><td>${money(n(e.qty)*n(e.unitPrice))}</td><td><button class="btn danger er" data-i="${i}">×</button></td></tr>`).join("")||`<tr><td colspan="6"><div class="empty">No essentials yet.</div></td></tr>`;
$("#mealTarget").textContent=money(target());$("#recipes").innerHTML=RECIPES.map(r=>`<div class="card recipe"><h3>${r.name}</h3><div class="tags">${r.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="small">${r.servings} servings · ${money(r.cost)}/batch</div><div class="kpi section"><span>Fits</span><b>${repeats(r)} more</b></div><div class="tools section"><button class="btn primary addMeal" data-id="${r.id}" ${repeats(r)<1?"disabled":""}>Add</button><button class="btn rmMeal" data-id="${r.id}">Remove</button><a class="btn" href="${search(r.q)}" target="_blank" rel="noopener">Recipe</a></div></div>`).join("");
let pe=Object.entries(state.plan).filter(x=>n(x[1])>0);$("#mealMeta").textContent=batches()+" of "+state.dinnerSlots;$("#planRows").innerHTML=pe.map(([id,c])=>{let r=RECIPES.find(x=>x.id===id),k=n(state.cooked[id]);return`<div class="row"><div><b>${r.name}</b><div class="small">planned ${c}× · cooked ${k}/${c}</div></div><button class="btn green cooked" data-id="${id}" ${k>=c?"disabled":""}>Cooked +1</button></div>`}).join("")||`<div class="empty">No meals selected.</div>`;
let g=grocery(),gd=g.filter(x=>state.purchased[x.key]).length;$("#purchasePct").textContent=(g.length?Math.round(gd/g.length*100):0)+"%";$("#shopping").innerHTML=g.map(x=>`<div class="row"><div class="tools"><input class="check buy" data-k="${encodeURIComponent(x.key)}" type="checkbox" ${state.purchased[x.key]?"checked":""}><div><b>${esc(x.name)}</b><div class="small">${Math.round(x.qty*100)/100} ${esc(x.unit)} · ${[...x.sources].join(" · ")}</div></div></div><div class="tools"><input class="field paid" style="width:92px" data-k="${encodeURIComponent(x.key)}" type="number" step=".01" placeholder="Paid" value="${state.purchaseCost[x.key]??""}"><a class="btn" href="${search(x.name+" grocery price "+state.zip)}" target="_blank" rel="noopener">Price</a></div></div>`).join("")||`<div class="empty">Add essentials or meals first.</div>`;
$$(".income").forEach(x=>x.value=state.income[x.dataset.k]||"");$("#incomeNote").value=state.income.note||"";$("#otherCash").value=state.otherCash||"";$("#budgetLeft").textContent=money(cashLeft());$("#incomeSummary").innerHTML=`<div class="kpi"><span>Gross salary avg</span><b>${money(salaryGross())}</b></div><div class="kpi"><span>After entered withholding</span><b>${money(salaryNet())}</b></div><div class="kpi"><span>Average tips</span><b>${money(tips())}</b></div><div class="kpi"><span>Tip range</span><b>${money(tips(state.income.tipsLow))}–${money(tips(state.income.tipsHigh))}</b></div>`;$("#cashSummary").innerHTML=`<div class="kpi"><span>Income</span><b>${money(income())}</b></div><div class="kpi"><span>Bills</span><b>−${money(billsMonth())}</b></div><div class="kpi"><span>Daily expenses</span><b>−${money(dailyMonth())}</b></div><div class="kpi"><span>Fuel</span><b>${fuelCost()==null?"MPG needed":"−"+money(fuelCost())}</b></div><div class="kpi"><span>Other</span><b>−${money(state.otherCash)}</b></div><div class="kpi"><span>Unallocated</span><b>${money(cashLeft())}</b></div><div class="small section">Average recurring bill load: ${money(billsAvg())}</div>`;
$("#billRows").innerHTML=state.bills.map((b,i)=>`<tr><td><input class="field bn" data-i="${i}" value="${esc(b.name)}"></td><td><input class="field ba" data-i="${i}" type="number" value="${n(b.amount)}"></td><td><input class="field bd" data-i="${i}" type="number" value="${b.dueDay||""}"></td><td><input class="field bf" data-i="${i}" type="number" value="${b.frequencyMonths||1}"></td><td><input class="field bs" data-i="${i}" type="month" value="${b.startMonth||ym()}"></td><td><button class="btn danger br" data-i="${i}">×</button></td></tr>`).join("")||`<tr><td colspan="6"><div class="empty">No bills entered.</div></td></tr>`;
$("#dailyRows").innerHTML=state.dailyExpenses.map((d,i)=>`<div class="row"><div class="grid g2"><input class="field dn" data-i="${i}" value="${esc(d.name)}"><input class="field da" data-i="${i}" type="number" step=".01" value="${n(d.amountPerDay)}"></div><div><b>${money(n(d.amountPerDay)*days())}/mo</b> <button class="btn danger dr" data-i="${i}">×</button></div></div>`).join("")||`<div class="empty">No daily expenses.</div>`;
$("#gasPrice").value=state.fuel.pricePerGal||"";$("#mpg").value=state.fuel.mpg||"";$("#station").value=state.fuel.station||"";$("#gasSearch").href=search((state.fuel.station||"gas station")+" current regular gas price "+state.zip);$("#fuelEstimate").textContent=fuelCost()==null?"Enter MPG":money(fuelCost());let inc=state.fuel.routes.filter(r=>!(n(r.miles)>0&&n(r.days)>0)).length;$("#driveStats").innerHTML=`<div class="stat"><small>Weekly miles</small><div class="value">${weeklyMiles().toFixed(1)}</div></div><div class="stat"><small>Monthly miles</small><div class="value">${Math.round(monthlyMiles()).toLocaleString()}</div></div><div class="stat"><small>Incomplete legs</small><div class="value">${inc}</div></div><div class="stat"><small>Gas rate</small><div class="value">${money(state.fuel.pricePerGal)}</div></div>`;
$("#routeRows").innerHTML=state.fuel.routes.map((r,i)=>{let ok=n(r.miles)>0&&n(r.days)>0;return`<tr><td><input class="field rn" data-i="${i}" value="${esc(r.name)}"></td><td><input class="field rm" data-i="${i}" type="number" step=".1" value="${r.miles??""}"></td><td><input class="field rd" data-i="${i}" type="number" value="${r.days??""}"></td><td>${ok?(n(r.miles)*n(r.days)).toFixed(1):"—"}</td><td><button class="btn danger rr" data-i="${i}">×</button></td></tr>`}).join("")||`<tr><td colspan="5"><div class="empty">No route legs.</div></td></tr>`;
$("#houseLabel").value=state.householdLabel||"";$("#ebtBudget").value=state.ebtBudget||"";$("#dinnerSlots").value=state.dinnerSlots||30;$("#zip").value=state.zip||"";
bind();save();
}
function bind(){
[["pn","name"],["pp","pack"],["pv","price"],["ps","store"]].forEach(([c,k])=>$$("."+c).forEach(x=>x.onchange=()=>{state.prices[+x.dataset.i][k]=k==="price"?n(x.value):x.value;render()}));
[["en","name"],["eq","qty"],["eu","unit"],["ep","unitPrice"]].forEach(([c,k])=>$$("."+c).forEach(x=>x.onchange=()=>{state.essentials[+x.dataset.i][k]=["qty","unitPrice"].includes(k)?n(x.value):x.value;render()}));$$(".er").forEach(x=>x.onclick=()=>{state.essentials.splice(+x.dataset.i,1);render()});
$$(".addMeal").forEach(x=>x.onclick=()=>{let r=RECIPES.find(y=>y.id===x.dataset.id);if(repeats(r)>0)state.plan[r.id]=n(state.plan[r.id])+1;render()});$$(".rmMeal").forEach(x=>x.onclick=()=>{let id=x.dataset.id;state.plan[id]=Math.max(0,n(state.plan[id])-1);if(!state.plan[id])delete state.plan[id];render()});$$(".cooked").forEach(x=>x.onclick=()=>{let id=x.dataset.id;state.cooked[id]=Math.min(n(state.plan[id]),n(state.cooked[id])+1);render()});
$$(".buy").forEach(x=>x.onchange=()=>{state.purchased[decodeURIComponent(x.dataset.k)]=x.checked;render()});$$(".paid").forEach(x=>x.onchange=()=>{state.purchaseCost[decodeURIComponent(x.dataset.k)]=x.value===""?"":n(x.value);save()});
[["bn","name"],["ba","amount"],["bd","dueDay"],["bf","frequencyMonths"],["bs","startMonth"]].forEach(([c,k])=>$$("."+c).forEach(x=>x.onchange=()=>{state.bills[+x.dataset.i][k]=["amount","dueDay","frequencyMonths"].includes(k)?n(x.value):x.value;render()}));$$(".br").forEach(x=>x.onclick=()=>{state.bills.splice(+x.dataset.i,1);render()});
$$(".dn").forEach(x=>x.onchange=()=>{state.dailyExpenses[+x.dataset.i].name=x.value;render()});$$(".da").forEach(x=>x.onchange=()=>{state.dailyExpenses[+x.dataset.i].amountPerDay=n(x.value);render()});$$(".dr").forEach(x=>x.onclick=()=>{state.dailyExpenses.splice(+x.dataset.i,1);render()});
$$(".rn").forEach(x=>x.onchange=()=>{state.fuel.routes[+x.dataset.i].name=x.value;render()});$$(".rm").forEach(x=>x.onchange=()=>{state.fuel.routes[+x.dataset.i].miles=x.value===""?"":n(x.value);render()});$$(".rd").forEach(x=>x.onchange=()=>{state.fuel.routes[+x.dataset.i].days=x.value===""?"":n(x.value);render()});$$(".rr").forEach(x=>x.onclick=()=>{state.fuel.routes.splice(+x.dataset.i,1);render()});
}
function setupEvents(){
$("#addPrice").onclick=()=>{state.prices.push({id:"p"+Date.now(),name:"New item",pack:"",price:0,store:""});render()};$("#addEssential").onclick=()=>{state.essentials.push({id:"e"+Date.now(),name:"New essential",qty:1,unit:"item",unitPrice:0,store:""});render()};$("#addBill").onclick=()=>{state.bills.push({id:"b"+Date.now(),name:"New bill",amount:0,dueDay:"",frequencyMonths:1,startMonth:ym()});render()};$("#addDaily").onclick=()=>{state.dailyExpenses.push({id:"d"+Date.now(),name:"Daily expense",amountPerDay:0});render()};$("#addRoute").onclick=()=>{state.fuel.routes.push({id:"r"+Date.now(),name:"Route leg",miles:"",days:""});render()};
$$(".income").forEach(x=>x.onchange=()=>{state.income[x.dataset.k]=n(x.value);render()});$("#incomeNote").onchange=e=>{state.income.note=e.target.value;render()};$("#otherCash").onchange=e=>{state.otherCash=n(e.target.value);render()};$("#gasPrice").onchange=e=>{state.fuel.pricePerGal=n(e.target.value);state.fuel.priceUpdated=new Date().toISOString().slice(0,10);render()};$("#mpg").onchange=e=>{state.fuel.mpg=e.target.value===""?"":n(e.target.value);render()};$("#station").onchange=e=>{state.fuel.station=e.target.value;render()};
$("#houseLabel").onchange=e=>{state.householdLabel=e.target.value||"My Household";render()};$("#ebtBudget").onchange=e=>{state.ebtBudget=n(e.target.value);render()};$("#dinnerSlots").onchange=e=>{state.dinnerSlots=Math.max(1,n(e.target.value)||30);render()};$("#zip").onchange=e=>{state.zip=e.target.value.trim();render()};
$("#recipeSearch").onclick=()=>open(search(($("#mealSearch").value.trim()||"budget dinner")+" recipe under "+money(target())+" per batch"),"_blank");
$("#exportBtn").onclick=()=>{let b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="family-planner-private.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$("#importFile").onchange=async e=>{let f=e.target.files?.[0];if(!f)return;try{let x=JSON.parse(await f.text());state=Object.assign(blank(),x,{version:2,profileLoaded:true});render();show(state.view||"home");alert("Private profile imported on this device.")}catch{alert("Invalid planner JSON.")}e.target.value=""};
$("#resetBtn").onclick=()=>{if(confirm("Clear all planner data from this browser?")){state=blank();render();show("home")}};
}
shell();nav();setupEvents();render();show(state.view||"home");
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));